ALLOWED_PRIMARY_QUESTION_TYPES = [
    "chart_diagram_interpretation",
    "parameter_relation_understanding",
    "local_constraint_or_causal_interpretation",
    "light_multi_hop_technical_reasoning",
]

ALLOWED_DEGRADED_QUESTION_TYPES = [
    "conservative_chart_interpretation",
    "single_hop_parameter_readout",
]

TECHNICAL_KEYWORDS = {
    "timing": [
        "timing",
        "latency",
        "trcd",
        "trp",
        "tras",
        "cas",
        "activate",
        "precharge",
        "read",
        "write",
        "cycle",
        "delay",
    ],
    "architecture": [
        "bank",
        "channel",
        "rank",
        "row",
        "column",
        "array",
        "controller",
        "path",
        "topology",
        "architecture",
        "organization",
        "block",
    ],
    "performance": [
        "bandwidth",
        "throughput",
        "performance",
        "speed",
        "faster",
        "slower",
        "improve",
        "penalty",
        "efficiency",
    ],
    "comparison": [
        "compare",
        "difference",
        "versus",
        "higher",
        "lower",
        "better",
        "worse",
        "tradeoff",
    ],
    "constraint": [
        "constraint",
        "depends",
        "requires",
        "limit",
        "before",
        "after",
        "impact",
        "cause",
        "affect",
    ],
}
