global_params:
  working_dir: cache
  graph_backend: kuzu # graph database backend, support: kuzu, networkx
  kv_backend: rocksdb # key-value store backend, support: rocksdb, json_kv

nodes:
  - id: read
    op_name: read
    type: source
    dependencies: []
    params:
      input_path:
        - examples/input_examples/txt_demo.txt

  - id: structure_analyze
    op_name: structure_analyze
    type: map_batch
    dependencies:
      - read
    execution_params:
      replicas: 2

  - id: hierarchy_generate
    op_name: hierarchy_generate
    type: map_batch
    dependencies:
      - structure_analyze
    execution_params:
      replicas: 2

  - id: tree_construct
    op_name: tree_construct
    type: map_batch
    dependencies:
      - hierarchy_generate
    execution_params:
      replicas: 2

  - id: tree_chunk
    op_name: tree_chunk
    type: map_batch
    dependencies:
      - tree_construct
    execution_params:
      replicas: 4
    params:
      chunk_size: 1024
      chunk_overlap: 100

  - id: build_tree_kg
    op_name: build_tree_kg
    type: map_batch
    execution_params:
      replicas: 1
      batch_size: 128
    dependencies:
      - tree_chunk

  - id: partition
    op_name: partition
    type: aggregate
    dependencies:
      - build_tree_kg
    params:
      method: dfs
      method_params:
        max_units_per_community: 1

  - id: generate
    op_name: generate
    type: map_batch
    dependencies:
      - partition
    execution_params:
      replicas: 1
      batch_size: 128
    save_output: true
    params:
      method: atomic
      data_format: Alpaca
