import argparse
import asyncio
import json
import logging
from pathlib import Path
from typing import List

import Levenshtein
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from tqdm import tqdm

from modora.core.domain.results import ResultItem, write_results_file
from modora.core.infra.llm import (
    AsyncLocalLLMClient,
    AsyncRemoteLLMClient,
    ensure_llm_local_loaded,
    shutdown_llm_local,
)
from modora.core.settings import Settings


class Evaluator:
    """Evaluator class for determining if generated answers are correct."""

    def __init__(
        self, settings: Settings, logger: logging.Logger, use_remote: bool = False
    ):
        self.settings = settings
        self.logger = logger
        if use_remote:
            self.llm = AsyncRemoteLLMClient(settings)
        else:
            self.llm = AsyncLocalLLMClient()

    async def check_answer(self, query: str, answer: str) -> bool:
        """Check if the answer is valid."""
        try:
            return await self.llm.check_answer(query, answer)
        except Exception as e:
            self.logger.error(f"Error in check_answer: {e}")
            return False

    async def is_equal(self, query: str, references: List[str], prediction: str) -> str:
        """Determine if the predicted answer is equivalent to the reference answer."""
        if not prediction:
            return "F"

        for reference in references:
            # Inclusion check: if the reference answer is contained in the prediction, it's considered correct
            if reference.lower() in prediction.lower():
                return "T"

            # AI-assisted check: use LLM to judge semantic consistency
            try:
                if await self.llm.evaluate(query, reference, prediction):
                    return "T"
            except Exception as e:
                self.logger.error(f"Error in is_equal AI check: {e}")

        return "F"

    def anls_single_sample(
        self, prediction: str, references: List[str], threshold: float = 0.5
    ) -> float:
        """Calculate the ANLS (Average Normalized Levenshtein Similarity) score for a single sample."""
        max_nls = 0.0
        pred_str = prediction if prediction is not None else ""

        for reference in references:
            distance = Levenshtein.distance(pred_str, reference)
            max_len = max(len(pred_str), len(reference))
            if max_len == 0:
                nls = 1.0
            else:
                nls = 1.0 - float(distance) / max_len

            if nls > max_nls:
                max_nls = nls

        return max_nls if max_nls > threshold else 0.0


def register(sub: argparse._SubParsersAction) -> None:
    """Register the evaluate sub-command."""
    parser = sub.add_parser("evaluate", help="Evaluate QA results")
    parser.add_argument(
        "--input",
        default=None,
        help="Path to the input JSON file (original dataset)",
    )
    parser.add_argument(
        "--result",
        default=None,
        help="Path to the result JSON file (generated by batch-qa)",
    )
    parser.add_argument(
        "--output",
        help="Path to save the evaluation report (JSONL) (default: same as --result parent dir)",
    )
    parser.add_argument(
        "--analyze",
        action="store_true",
        default=True,
        help="Whether to analyze the results and generate charts (default: True)",
    )
    parser.add_argument(
        "--concurrency",
        type=int,
        default=16,
        help="Max concurrent evaluation tasks",
    )
    parser.add_argument(
        "--remote",
        action="store_true",
        help="Use remote LLM defined in local.json for evaluation",
    )
    parser.set_defaults(_handler=_handle_evaluate)


async def _process_single_item(
    item: dict, prediction_map: dict, evaluator: Evaluator, sem: asyncio.Semaphore
) -> ResultItem | None:
    """Process a single evaluation item."""
    async with sem:
        try:
            qid = item.get("questionId")
            if qid not in prediction_map:
                # Missing prediction result
                return None

            pred_item = prediction_map[qid]
            prediction = pred_item.get("prediction")

            # Prepare reference answers list
            answer = item.get("answer", [])
            if isinstance(answer, str):
                answer = [answer]
            elif not isinstance(answer, list):
                # Fallback logic for complex datasets (e.g., DUDE)
                if "answers" in item:
                    answer = [", ".join(item["answers"])] + item.get(
                        "answers_variants", []
                    )
                else:
                    answer = []

            # AI evaluation
            judge = await evaluator.is_equal(item["question"], answer, prediction)

            # Special logic for unanswerable questions
            if item.get("answer_type") == "not-answerable" and (
                prediction is None or prediction == ""
            ):
                judge = "T"

            # Construct ResultItem
            result_item = ResultItem(
                questionId=qid,
                pdf_id=item.get("pdf_id", "") or str(item.get("image_id", "")),
                question=item["question"],
                answer=answer,
                tag=item.get("tag"),
                prediction=prediction,
                judge=judge,
            )
            return result_item

        except Exception as e:
            evaluator.logger.error(
                f"Error processing item {item.get('questionId')}: {e}"
            )
            return None


async def _run_evaluation(
    input_path: Path,
    result_path: Path,
    output_path: Path,
    concurrency: int,
    logger: logging.Logger,
    use_remote: bool = False,
):
    """Run the batch evaluation process."""
    settings = Settings.load()
    evaluator = Evaluator(settings, logger, use_remote=use_remote)

    # Load dataset and prediction results
    with open(input_path, "r", encoding="utf-8") as f:
        dataset = json.load(f)

    with open(result_path, "r", encoding="utf-8") as f:
        results_data = json.load(f)

    # Compatibility handling: if result.json is in dictionary format {"results": [...], "metrics": {...}}
    if isinstance(results_data, dict) and "results" in results_data:
        results = results_data["results"]
    else:
        results = results_data

    # Map prediction results by ID for quick lookup
    prediction_map = {r["questionId"]: r for r in results}

    sem = asyncio.Semaphore(concurrency)
    tasks = [
        _process_single_item(item, prediction_map, evaluator, sem) for item in dataset
    ]

    evaluated_items = []
    for f in tqdm(asyncio.as_completed(tasks), total=len(tasks), desc="Evaluating"):
        res = await f
        if res:
            evaluated_items.append(res)

    # Save evaluation results
    output_path.parent.mkdir(parents=True, exist_ok=True)
    write_results_file(str(output_path), evaluated_items)

    # Calculate metrics
    total = len(evaluated_items)
    correct = sum(1 for item in evaluated_items if item.judge == "T")
    accuracy = correct / total if total > 0 else 0.0

    anls_score = 0.0
    for item in evaluated_items:
        if item.judge == "T":

            contain = False
            if item.prediction:
                for ans in item.answer:
                    if ans and ans.lower() in item.prediction.lower():
                        contain = True
                        break

            if contain:
                anls_score += 1.0
            elif item.answer == [] or (
                item.prediction is None and item.judge == "T"
            ):  # Approximate handling for unanswerable questions
                anls_score += 1.0
            else:
                anls_score += evaluator.anls_single_sample(item.prediction, item.answer)
        else:
            anls_score += evaluator.anls_single_sample(item.prediction, item.answer)

    anls = anls_score / total if total > 0 else 0.0

    # Save metrics back to result.json
    try:
        with open(result_path, "r", encoding="utf-8") as f:
            results_data = json.load(f)

        metrics = {
            "total": total,
            "correct": correct,
            "accuracy": round(accuracy, 4),
            "anls": round(anls, 4),
        }

        if isinstance(results_data, list):
            output_data = {"metrics": metrics, "results": results_data}
        else:
            results_data["metrics"] = metrics
            output_data = results_data

        with open(result_path, "w", encoding="utf-8") as f:
            json.dump(output_data, f, ensure_ascii=False, indent=2)
        print(f"Metrics saved to {result_path}")
    except Exception as e:
        logger.error(f"Failed to save metrics to result.json: {e}")

    print("\nEvaluation Complete.")
    print(f"Total: {total}")
    print(f"Accuracy: {accuracy:.4f}")
    print(f"ANLS: {anls:.4f}")
    print(f"Detailed results saved to {output_path}")

    return evaluated_items, metrics


def _plot_results(
    evaluated_items: List[ResultItem], output_dir: Path, overall_metrics: dict = None
):
    """Generate charts and summary CSV based on evaluation results.

    Args:
        evaluated_items: List of evaluated result items.
        output_dir: Directory to save the output.
        overall_metrics: Overall evaluation metrics.
    """
    if not evaluated_items:
        print("No data to plot.")
        return

    data = []
    for item in evaluated_items:
        tag = item.tag or "Unknown"
        category = "Unknown"
        if isinstance(tag, str) and "-" in tag:
            try:
                # Follow the logic in analyze_eval.py, take the part after the hyphen
                category = tag.split("-")[-1]
            except Exception:
                pass

        # Calculate ACNLS (Inclusion check + ANLS)
        acnls = 0.0
        contain = False
        pred_str = str(item.prediction).lower() if item.prediction is not None else ""

        if item.answer:
            for ans in item.answer:
                ans_str = str(ans).lower()
                if ans_str and ans_str in pred_str:
                    contain = True
                    break

        if contain:
            acnls = 1.0
        else:
            # The ANLS calculation logic here reuses the implementation in Evaluator, but with threshold=0.5
            # A threshold of 0.5 was used in analyze_eval.py
            max_nls = 0.0
            for ref in item.answer:
                ref_str = str(ref).lower()
                dist = Levenshtein.distance(pred_str, ref_str)
                max_len = max(len(pred_str), len(ref_str))
                nls = 1.0 - (dist / max_len) if max_len > 0 else 1.0
                max_nls = max(max_nls, nls)
            acnls = max_nls if max_nls > 0.5 else 0.0

        data.append(
            {
                "tag": tag,
                "category": category,
                "Accuracy": 1.0 if item.judge == "T" else 0.0,
                "ACNLS": acnls,
            }
        )

    df = pd.DataFrame(data)
    output_dir.mkdir(parents=True, exist_ok=True)

    # Grouped statistics
    grouped = df.groupby("tag")[["Accuracy", "ACNLS"]].mean().reset_index()
    grouped = grouped.sort_values("tag")

    sns.set_theme(style="whitegrid")

    # 1. Plot Accuracy per Tag
    plt.figure(figsize=(12, 6))
    ax = sns.barplot(
        x="tag", y="Accuracy", data=grouped, hue="tag", palette="viridis", legend=False
    )
    plt.title("Accuracy per Tag", fontsize=16)
    plt.ylim(0, 1.1)
    for p in ax.patches:
        ax.annotate(
            f"{p.get_height():.2f}",
            (p.get_x() + p.get_width() / 2.0, p.get_height()),
            ha="center",
            va="center",
            xytext=(0, 9),
            textcoords="offset points",
        )
    plt.tight_layout()
    plt.savefig(output_dir / "accuracy_per_tag.png")
    plt.close()

    # 2. Plot ACNLS per Tag
    plt.figure(figsize=(12, 6))
    ax = sns.barplot(
        x="tag", y="ACNLS", data=grouped, hue="tag", palette="magma", legend=False
    )
    plt.title("ACNLS per Tag", fontsize=16)
    plt.ylim(0, 1.1)
    for p in ax.patches:
        ax.annotate(
            f"{p.get_height():.2f}",
            (p.get_x() + p.get_width() / 2.0, p.get_height()),
            ha="center",
            va="center",
            xytext=(0, 9),
            textcoords="offset points",
        )
    plt.tight_layout()
    plt.savefig(output_dir / "acnls_per_tag.png")
    plt.close()

    # 3. Save Summaries
    grouped.to_csv(output_dir / "metrics_summary_by_tag.csv", index=False)

    category_grouped = (
        df.groupby("category")[["Accuracy", "ACNLS"]].mean().reset_index()
    )
    category_grouped = category_grouped.sort_values("category")
    category_grouped.to_csv(output_dir / "metrics_summary_by_category.csv", index=False)

    # 4. Plot Category Metrics
    for metric in ["Accuracy", "ACNLS"]:
        plt.figure(figsize=(10, 6))
        palette = "viridis" if metric == "Accuracy" else "magma"
        ax = sns.barplot(
            x="category",
            y=metric,
            data=category_grouped,
            hue="category",
            palette=palette,
            legend=False,
        )
        plt.title(f"{metric} per Category", fontsize=16)
        plt.ylim(0, 1.1)
        for p in ax.patches:
            ax.annotate(
                f"{p.get_height():.2f}",
                (p.get_x() + p.get_width() / 2.0, p.get_height()),
                ha="center",
                va="center",
                xytext=(0, 9),
                textcoords="offset points",
            )
        plt.tight_layout()
        plt.savefig(output_dir / f"{metric.lower()}_per_category.png")
        plt.close()

    # 5. Save Overall Metrics if provided
    if overall_metrics:
        with open(output_dir / "overall_metrics.json", "w", encoding="utf-8") as f:
            json.dump(overall_metrics, f, ensure_ascii=False, indent=2)

    print(f"\nAnalysis results (charts and CSVs) saved to {output_dir}")
    print("\nSummary by Tag:")
    print(grouped)
    print("\nSummary by Category:")
    print(category_grouped)
    print("\nOverall Metrics:")
    print(df[["Accuracy", "ACNLS"]].mean())


def _handle_evaluate(args: argparse.Namespace, logger: logging.Logger) -> int:
    """Handler for the evaluate command.

    Args:
        args: Command line arguments.
        logger: Logger instance.

    Returns:
        int: Exit code (0 for success, 1 for failure).
    """
    # Ensure local LLM is loaded only when not using remote LLM
    settings = Settings.load()
    if not args.remote:
        ensure_llm_local_loaded(settings, logger, force=True)
    try:
        input_value = (getattr(args, "input", None) or "").strip()
        result_value = (getattr(args, "result", None) or "").strip()
        input_path = Path(
            input_value or (Path(settings.docs_dir or "") / "test.json")
        ).resolve()
        result_path = Path(
            result_value or (Path(settings.cache_dir or "") / "result.json")
        ).resolve()
        output_path = (
            Path(args.output)
            if args.output
            else result_path.parent / "evaluation.jsonl"
        )

        evaluated_items, metrics = asyncio.run(
            _run_evaluation(
                input_path,
                result_path,
                output_path,
                args.concurrency,
                logger,
                use_remote=args.remote,
            )
        )

        if args.analyze:
            _plot_results(evaluated_items, output_path.parent, overall_metrics=metrics)

        return 0
    except Exception as e:
        logger.error(f"Evaluation failed: {e}")
        return 1
    finally:
        if not args.remote:
            shutdown_llm_local()
